/**
 * This file is auto-generated by core/tools/update_utils_errcodes.py
 * 
 * DO NOT EDIT!!!
 * 
 * If something is wrong, please fix it in core/tools/templates/update_utils_errcodes/errcodes.h.in first
 */

#ifndef _TINA_CORE_UTILS_ERRCODES_H_
#define _TINA_CORE_UTILS_ERRCODES_H_

#include<string>
#include<unordered_map>

namespace tina::core::utils {

    class errcodes {

        public:
            errcodes() = delete;
            errcodes( const errcodes& ) = delete;
            ~errcodes() = delete;
            errcodes& operator=( const errcodes& ) = delete;

        public:
            typedef enum sql : int {
                OK = 0,
                SQL_NOT_OPEN = 1,
            } sql;

            static std::string get_name( sql __ec_code );

        private:
            static const std::unordered_map<sql,std::string> _um_sql_namemap;

    }; // class errcodes

} // namespace tina::core::utils

#endif // _TINA_CORE_UTILS_ERRCODES_H_
