/**
 * This file is auto-generated by core/tools/update_utils_errcodes.py
 * 
 * DO NOT EDIT!!!
 * 
 * If something is wrong, please fix it in core/tools/templates/update_utils_errcodes/errcodes.cpp.in first
 */

#include"core/utils/errcodes.h"

#include<stdexcept>

namespace utils = tina::core::utils;

std::string utils::errcodes::get_name( utils::errcodes::g3log_sink __ec_code ){
    try {
        return _um_g3log_sink_namemap.at( __ec_code );
    }
    catch ( std::out_of_range )
    {
        return "";
    }
}

std::string utils::errcodes::get_name( utils::errcodes::sql __ec_code ){
    try {
        return _um_sql_namemap.at( __ec_code );
    }
    catch ( std::out_of_range )
    {
        return "";
    }
}

std::string utils::errcodes::get_name( utils::errcodes::sql_cb __ec_code ){
    try {
        return _um_sql_cb_namemap.at( __ec_code );
    }
    catch ( std::out_of_range )
    {
        return "";
    }
}

const std::unordered_map<utils::errcodes::g3log_sink,std::string> utils::errcodes::_um_g3log_sink_namemap = {
    { G3LOG_SINK_LOGFILE_NOT_OPEN , "G3LOG_SINK_LOGFILE_NOT_OPEN" },
};

const std::unordered_map<utils::errcodes::sql,std::string> utils::errcodes::_um_sql_namemap = {
    { SQL_DB_NOT_OPEN , "SQL_DB_NOT_OPEN" },
    { SQL_ILLEGAL_DB , "SQL_ILLEGAL_DB" },
    { SQL_CREATE_TABLE_FAILED , "SQL_CREATE_TABLE_FAILED" },
    { SQL_WRITE_FORMAT_FAILED , "SQL_WRITE_FORMAT_FAILED" },
    { SQL_WRITE_HEADER_FAILED , "SQL_WRITE_HEADER_FAILED" },
    { SQL_WRITE_HASH_FAILED , "SQL_WRITE_HASH_FAILED" },
    { SQL_WRITE_TAG_FAILED , "SQL_WRITE_TAG_FAILED" },
    { SQL_WRITE_CALENDAR_FAILED , "SQL_WRITE_CALENDAR_FAILED" },
    { SQL_WRITE_NOTES_FAILED , "SQL_WRITE_NOTES_FAILED" },
    { SQL_UNEXCEPTED , "SQL_UNEXCEPTED" },
};

const std::unordered_map<utils::errcodes::sql_cb,std::string> utils::errcodes::_um_sql_cb_namemap = {
    { SQL_CB_ILLEGAL_ARGC , "SQL_CB_ILLEGAL_ARGC" },
    { SQL_CB_OVERWRITE_EXISTING_DATA , "SQL_CB_OVERWRITE_EXISTING_DATA" },
    { SQL_CB_ROOT_HASH_REDEFINE , "SQL_CB_ROOT_HASH_REDEFINE" },
    { SQL_CB_ILLEGAL_HASH_ID , "SQL_CB_ILLEGAL_HASH_ID" },
    { SQL_CB_ILLEGAL_HASH , "SQL_CB_ILLEGAL_HASH" },
    { SQL_CB_ILLEGAL_EMAIL_ADDR , "SQL_CB_ILLEGAL_EMAIL_ADDR" },
    { SQL_CB_UNEXCEPTED , "SQL_CB_UNEXCEPTED" },
};

